version: '3.8'

services:
  rag-service:
    build: .
    container_name: rag-knowledge-retrieval
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ../ai_models:/app/ai_models
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0  # 如果使用GPU，取消注释此行
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  # 可选：添加Redis用于缓存
  redis:
    image: redis:7-alpine
    container_name: rag-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # 可选：添加Nginx用于负载均衡
  nginx:
    image: nginx:alpine
    container_name: rag-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rag-service
    restart: unless-stopped

volumes:
  redis_data:
